# -*- coding: utf-8 -*-
"""exe1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BADx4e2PsN5v46SdRppNaday038_bg8N
"""

L = "AABBEFAAT"
R = "BE"
a = L.find(R) ##Variável com o resultado da procura de "BE" em L.

print(f"{R} encontrado na posição {a:{0}} de {L}")
